# Generated by Django 2.2.7 on 2019-12-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20191205_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
