# Generated by Django 2.2.7 on 2019-12-06 12:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content2',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
