# Generated by Django 2.2.7 on 2019-12-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0003_article_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content2',
        ),
    ]
