# Generated by Django 2.2.7 on 2019-12-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0009_userextend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='fk.Tag'),
        ),
    ]
