# Generated by Django 2.2.7 on 2019-12-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('front', '0003_auto_20191206_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyArticle',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('front.article',),
        ),
    ]
